# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HierarCluster_paris <- function(m) {
    .Call(`_HGC_core_HierarCluster_paris`, m)
}

HierarCluster_paris_time <- function(m) {
    .Call(`_HGC_core_HierarCluster_paris_time`, m)
}

get_leaves <- function(hglink) {
    .Call(`_HGC_core_get_leaves`, hglink)
}

